baseURL = 'https://timeline.abrahamsustaita.com/'
languageCode = 'en-us'
title = 'Timeline Generator'

[params]
  contentTypeName = "posts"
  description = "A terminal-style technical blog"
  enableGitInfo = true
  favicon = "favicon.ico"
  fullWidthTheme = true
  showLastUpdated = false
  googleClientId = "103086197912-a1plob9pg1hj4kuk7d5lsn0rcntd8kjg.apps.googleusercontent.com"

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
